---
- hosts: all
  become: true

  pre_tasks:
    - name: vars
      include_vars: vars.yml

    - name: install packages
      import_tasks: tasks/packages.yml

  tasks:
    - name: download Controller from tplink
      import_tasks: tasks/setup.yml
      when: omada_preset.rc == 1

    - name: Install Omada
      import_tasks: tasks/omada.yml

    - name: Get cotroller url
      import_tasks: tasks/ip.yml

handlers:
    - name: Reboot
      reboot: