---

- name: make {{ omada_dir }}install.sh exicutable
  file:
    path: "{{ omada_dir }}/install.sh"
    mode: a+x

- name: Install Omada
  command: "./install.sh -y -n"
  args:
    chdir: "{{ omada_dir }}"
  register: omadainstall
  when: omada_preset.rc == 1

- name: omada install status
  debug:
    msg: "{{ omadainstall.stdout_lines }}"
  when: omada_preset.rc == 1

- name: make sure Omada is runnig.
  service:
    name: tpeap
    state: started
    enabled: true
