---

- name: Install Omada
  become: yes
  command: install.sh -y -n
  args:
    chdir: /home/ansible/omada/
  register: omadainstall
  when: omada_preset.rc == 1

- name: omada install status 
  debug:
    msg: "{{ omadainstall.stdout_lines }}"
  when: omada_preset.rc == 1

- name: make sure Omada is runnig.
  service:
    name: tpeap
    state: started
    enabled: true


