---

- name: Run apt cache update & upgrade
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    state: latest

- name: Create man Directory(fix java install issue)
  ansible.builtin.file:
    path: /usr/share/man/man1
    state: directory
    mode: '0755'

- name: Run apt install packages
  ansible.builtin.apt:
    name:
      - mongodb
      - jsvc
      - curl
      - openjdk-8-jre-headless
    state: present
    update_cache: true

- name: Ensure mongo is running on debian.
  ansible.builtin.service:
    name: mongodb
    state: started
    enabled: true

- name: Check mongodb install status
  ansible.builtin.command: which mongodb
  failed_when: false
  changed_when: false
  check_mode: false
  register: mongo_preset
