---

- name: apt cache update & upgrade
  apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: full
  when: ansible_facts.os_family == "Debian"

- name: apt install packages
  apt:
    name:
      - mongodb
      - jsvc
      - curl
      - openjdk-8-jre-headless
    state: present
    cache_valid_time: 3600
  when: ansible_facts.os_family == "Debian"

- name: yum cache update & upgrade
  yum:
    name: "*"
    state: latest
    update_cache: true
  when: ansible_facts.os_family == "RedHat"

- name: yum install packages
  yum:
    name:
      - curl
      - java-1.8.0-openjdk-headless.x86_64
      - jsvc
      - tar
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install mongodb from rpm
  yum:
    name: " {{ mongo_url }} "
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Ensure mongo is runnig on debian.
  service:
    name: mongodb
    state: started
    enabled: true
  when: ansible_facts.os_family == "Debian"

- name: Ensure mongo is runnig on redhat.
  service:
    name: mongod
    state: started
    enabled: true
  when: ansible_facts.os_family == "RedHat"


- name: is mongodb installed
  command: which mongodb
  failed_when: false
  changed_when: false
  check_mode: false
  register: mongo_preset

- name: is Omada installed
  command: which tpeap
  failed_when: false
  changed_when: false
  check_mode: false
  register: omada_preset
