---

- name: Enable EPEL Repository on CentOS 7
  ansible.builtin.yum:
    name: epel-release
    state: latest

- name: yum cache update & upgrade
  ansible.builtin.yum:
    name: "*"
    state: latest
    update_cache: true

- name: yum install packages on rhel7
  ansible.builtin.yum:
    name:
      - numactl
      - python-pip
      - curl
      - java-1.8.0-openjdk-headless.x86_64
      - tar
    state: present

- name: install yum lux rpm key
  ansible.builtin.rpm_key:
    key: http://repo.iotti.biz/RPM-GPG-KEY-LUX
    state: present

- name: Copy jsvc rpm file to server
  copy:
     src: config/rpm/
     dest: /tmp/

- name: install jsvc on rhel 7
  ansible.builtin.yum:
    name: /tmp/apache-commons-daemon-jsvc-1.0.13-7.el7.x86_64.rpm
    state: present

- name: Mongodb 4.0 gpg key
  ansible.builtin.rpm_key:
    key: https://www.mongodb.org/static/pgp/server-4.0.asc
    state: present

- name: Install mongodb from rpm on rhel
  ansible.builtin.yum:
    name: /tmp/mongodb-org-server-4.0.27-1.el7.x86_64.rpm
    state: present

- name: Ensure mongo is runnig on redhat.
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: true

- name: is mongodb installed
  ansible.builtin.command: which mongodb
  failed_when: false
  changed_when: false
  check_mode: false
  register: mongo_preset

- name: is Omada installed
  ansible.builtin.command: which tpeap
  failed_when: false
  changed_when: false
  check_mode: false
  register: omada_preset
