---

- name: Create Omada Directory
  ansible.builtin.file:
    path: "{{ omada_dir }}"
    state: directory
    mode: '0755'

- name: Download & unzip the archive
  ansible.builtin.unarchive:
    src: "{{ omada_url }}"
    dest: "{{ omada_dir }}"
    remote_src: 'yes'
    extra_opts:
      --strip-components=1

- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required
